server:
  port: 8980
  
spring:
  # Database configuration
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:postgis}
    username: ${DB_USER:postgis}
    password: ${DB_PASSWORD:postgis}
  # JPA configuration  
  jpa:
    hibernate:
      ddl-auto: update
      # Avoid issue with JPA case insensitive
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    # This should no longer be needed with Hibernate 6
    # database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
    #    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

    database: postgresql
    # PotGIS configuration
    properties:
      hibernate:
#        jdbc:
#          lob:
#            non_contextual_creation: true
# No longer required in Hibernate 6
#        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
logging:
  level:
    org.hibernate.type.descriptor.sql: trace