apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: postgis
  name: postgis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgis
  template:
    metadata:
      labels:
        io.kompose.service: postgis
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: postgis
            - name: POSTGRES_PASSWORD
              value: postgis
            - name: POSTGRES_USER
              value: postgis
          image: postgis/postgis
          name: postgis
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgis-claim
      restartPolicy: Always
      volumes:
        - name: postgis-claim
          hostPath:
            path: /run/desktop/mnt/host/g/data/postgis
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: postgis
  name: postgis
spec:
  ports:
    - name: "5433"
      port: 5433
      targetPort: 5432
  selector:
    io.kompose.service: postgis
  type: LoadBalancer